services:
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/build
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  

volumes:
  static:
  frontend: