# Generated by Django 5.1 on 2024-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0002_route_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
