# Generated by Django 5.1 on 2024-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0003_alter_route_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='runactivity',
            name='paused',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
