name: Run Backend Unit Tests on PR

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_DATABASE_USER: ${{ secrets.TEST_DATABASE_USER }}
      TEST_DATABASE_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
      TEST_DATABASE_HOST: ${{ secrets.TEST_DATABASE_HOST }}
      TEST_DATABASE_PORT: ${{ secrets.TEST_DATABASE_PORT }}
      TEST_DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run migrations
      run: |
        cd backend
        python manage.py migrate

    - name: Run tests
      run: |
        cd backend
        pytest